name: ci-cd (mac/linux)

on: [push]
    
jobs:
  ember-build:
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ember-build
          environment-file: environment.yaml
          miniforge-version: latest
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}
      
      - name: install compiler
        run: mamba install cxx-compiler

      - name: scons build
        run: |
          conda activate ember-build
          scons build

      - name: View build logs (only on failure)
        if: failure()
        run: cat config.log

      - name: scons install
        run: scons install 

